spring:
  application:
    name: course

  datasource:
    url: jdbc:mysql://localhost:3306/Person?useTimezone=true&serverTimezone=UTC
    username: root
    password:    # ajuste se necessï¿½rio
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  open-in-view: false
logging:
    level:
      root: WARN
      #com.udemyCourse.course: WARN